version: '3.8'

services:
    php:
      build:
        context: .
        dockerfile: "./fdt-s2/admin/Dockerfile"
      container_name: php 
      ports: 
      - "8004:80"
      volumes: 
      - "./fdt-s2/admin/src:/var/www/html/"
      links:
      - "db:db"
      networks:
      - network-billingbox
      
    php2:
      build:
        context: .
        dockerfile: "./fdt-s2/landing/Dockerfile"
      container_name: php2
      ports: 
      - "80:80"
      volumes: 
      - "./fdt-s2/landing/src:/var/www/html/"
      links:
      - "db:db"
      networks:
      - network-billingbox
      
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      container_name: db
      environment:
      - MYSQL_ROOT_PASSWORD=toor
      volumes:
      - mysql-data:/var/lib/mysql
      networks:
      - network-billingbox

    adminer:
      image: adminer
      restart: always
      container_name: adimer
      ports:
        - 8080:8080
      networks:
      - network-billingbox

networks:
   network-billingbox:
    driver: bridge

volumes:
  mysql-data: